version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mean_network
  backend:
    image: ${DOCKER_USERNAME}/mean-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongodb:27017/cruddb
    depends_on:
      - mongodb
    networks:
      - mean_network

  frontend:
    image: ${DOCKER_USERNAME}/mean-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mean_network

  nginx:
    image: ${DOCKER_USERNAME}/mean-nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mean_network

volumes:
  mongo_data:

networks:
  mean_network:
    driver: bridge