version: '3.8'

services:
  backend:
    image: ssanyam2004/mean-backend:latest
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - MONGO_URI=${MONGO_URI}
    networks:
      - mean_network

  frontend:
    image: ssanyam2004/mean-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - mean_network

  nginx:
    image: ssanyam2004/mean-nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mean_network

networks:
  mean_network:
    driver: bridge